apiVersion: autoscaling/v2
kind: HinsightfintalPodAutoscaler
metadata:
  name: ai-service
  namespace: insightfin
  labels:
    app.kubernetes.io/name: ai-service
    app.kubernetes.io/part-of: insightfin
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
