apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: orizon
  labels:
    app.kubernetes.io/name: ai-service
    app.kubernetes.io/part-of: orizon
    app.kubernetes.io/component: ai
spec:
  selector:
    app.kubernetes.io/name: ai-service
  ports:
    - port: 8081
      targetPort: 8081
