package com.orizon.coreapi.domain.model;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Unified view over the two kinds of user-facing notifications: AI feedbacks
 * generated by the ai-service and budget threshold alerts generated when a
 * transaction crosses 50/80/100% of a category budget.
 *
 * <p>Sealed because the union is exhaustive — adding a third kind requires
 * adding a permits clause and a new subtype, which the compiler enforces.
 */
public sealed interface Notification permits AiFeedbackNotification, BudgetAlertNotification {

    UUID id();

    NotificationKind kind();

    boolean read();

    LocalDateTime createdAt();
}
