apiVersion: autoscaling/v2
kind: HinsightfintalPodAutoscaler
metadata:
  name: core-api
  namespace: insightfin
  labels:
    app.kubernetes.io/name: core-api
    app.kubernetes.io/part-of: insightfin
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: core-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
