apiVersion: v1
kind: Service
metadata:
  name: core-api
  namespace: insightfin
  labels:
    app.kubernetes.io/name: core-api
    app.kubernetes.io/part-of: insightfin
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: core-api
  ports:
    - port: 8080
      targetPort: 8080
